baseurl = "http://pchudzik.com/"
languageCode = "en-us"
title = "Paweł Chudzik"

# to install theme mkdir themes && git clone git@github.com:digitalcraftsman/hugo-creative-theme.git
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "Paweł Chudzik"
	description = "Paweł Chudzik homepage"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	analyticsCode = "UA-85460417-1"

	# Navigation
	[params.navigation]
		brand = "Paweł Chudzik"

		[params.navigation.links]
			about	 = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan	 = "Paweł Chudzik"
		subtitle   = "Eager to learn<br>IT consultant<br>Java developer<br>Javascript developer<br>Clean code enthusiast<br>Automated testing fan<br>Perfect software architecture chaser"
		buttonText = "Find out more"

	# About section
	[params.about]
		headline	= "About me"
		description = "My name is Paweł Chudzik I live in Królewiec small vilage next to Mińsk Mazowiecki in Poland. I'm software engineer with 6+ years of experience in solving complex and trival problems. During my career I have been developing a lot of things from big and complicated systems to small few liners to make life easier. I have expierence in variety of technologies, web frameworks, application servers, databases and tools. I care about good quality software. In pursuit to find perfect code I'm constantly improving my skills by learning new technologies and frameworks."
		buttonText  = "Get started!"
		buttonLink = "#contact"


	# Service section
	[params.services]
		headline = "At your service"

		[[params.services.list]]
			icon = "fa-code"
			title = "Software development"
			description = "Well-tested good quality software which works."

		[[params.services.list]]
			icon = "fa-paper-plane"
			title = "Agile partices"
			description = "Customer satisfaction is achievable by early and continuous delivery of valuable software."

		[[params.services.list]]
			icon = "fa-cog"
			title = "Software arhitecture"
			description = "The important stuff - whatever that is. Always trying to maximize the amount of work not needed to be done."

		[[params.services.list]]
			icon = "fa-users"
			title = "Team managment"
			description = "Best architectures, requirements, and designs emerge from self - organizing teams"

		[[params.services.list]]
			icon = "fa-puzzle-piece"
			title = "Technology advice"
			description = "Sometimes it hard to decide where to start."

		[[params.services.list]]
			icon = "fa-terminal"
			title = "Development environment"
			description = "Continuous integration & Continous delivery setup"

		[[params.services.list]]
			icon = "fa-newspaper-o"
			title = "Up to date"
			description = "Up to date with new technologies and methodologies."

		[[params.services.list]]
			icon = "fa-heart"
			title = "Made with Love"
			description = "You have to write your code with love these days!"


	# Portfolio modals
	[params.portfolio]
		title = "Portfolio"

	[params.portfolio.modal]
		#client = "Client"
		#date = "Date"
		category = "Category"
		buttonText = "Close"

	# Aside section
	#[params.aside]
	#	headline = "Visit my personal blog"
	#	[params.aside.button]
	#		text = "Go now!"
	#		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with me? That's great! Give me a call or send me an email and I will get back to you as soon as possible!"
		phone = "+48 503 695 927"
		email = "pawel.chudzik@gmail.com"
		githubUser = "pchudzik"
		githubLink = "https://github.com/pchudzik"
